name: CI check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Install Dependencies
        run: |
          set -x
          brew update
          brew install glfw

      - name: Build
        run: make
